### ISSUE TITLE
Files not linked properly in index.html

### ISSUE THREAD

**Issue by jainaayush01** [kcoder63/CertificateGenerator#6]
It is not generating a certificate as well.

![image](https://user-images.githubusercontent.com/54480934/113867981-d0f87b00-97cc-11eb-8efb-5901f2d9d307.png)

![image](https://user-images.githubusercontent.com/54480934/113868039-dfdf2d80-97cc-11eb-84f7-a0a071b6d0dd.png)

![image](https://user-images.githubusercontent.com/54480934/113868249-1b79f780-97cd-11eb-9baf-4c5155eb0b1a.png)

**Comment by kcoder63** [comment]
Thank you for raising the issue, will fix it soon

**Comment by kcoder63** [comment]
fixed PR #7 #8
